/* Search across every archive page.
 *
 * Loaded only by search.html. The index it fetches is generated by
 * scripts/build.py and lists the title, section and category of every page
 * on the site.
 */
(function () {
  'use strict';

  var INDEX_URL = 'search-index.json';
  var MAX_RESULTS = 60;

  var form = document.querySelector('[data-search-form]');
  var input = document.querySelector('[data-search-input]');
  var status = document.querySelector('[data-search-status]');
  var list = document.querySelector('[data-search-results]');
  var filters = document.querySelector('[data-search-filters]');
  if (!form || !input || !status || !list) { return; }

  var index = null;
  var loading = false;
  var pending = null;
  var section = 'all';

  /* Strip accents and punctuation so "Fuji-film" matches "fujifilm". */
  function normalise(text) {
    var flat = text.toLowerCase();
    if (String.prototype.normalize) {
      flat = flat.normalize('NFKD').replace(/[\u0300-\u036f]/g, '');
    }
    return flat.replace(/[^a-z0-9]+/g, ' ').replace(/\s+/g, ' ').trim();
  }

  function urlFor(doc) {
    var path = index.prefixes[doc[0]] + doc[1] + (doc[4] ? '/' : '.html');
    return path === '/' ? 'index.html' : path;
  }

  function score(doc, query, tokens) {
    var haystack = doc.search;
    var title = doc.normTitle;
    var i, token, at, points = 0;

    for (i = 0; i < tokens.length; i++) {
      token = tokens[i];
      at = haystack.indexOf(token);
      if (at === -1) { return 0; }
      // A match at the start of a word is worth more than one buried inside.
      points += (at === 0 || haystack.charAt(at - 1) === ' ') ? 12 : 4;
    }
    if (title.indexOf(query) === 0) { points += 120; }
    else if (title.indexOf(query) !== -1) { points += 60; }
    // Nudge concise titles above long ones that merely contain the words.
    points += Math.max(0, 40 - title.length) / 10;
    return points;
  }

  function prepare(data) {
    var docs = data.docs;
    for (var i = 0; i < docs.length; i++) {
      var doc = docs[i];
      doc.normTitle = normalise(doc[2]);
      doc.search = normalise(doc[2] + ' ' + data.labels[doc[0]] + ' ' + doc[1]);
    }
    return data;
  }

  function render(matches, query) {
    list.textContent = '';
    if (!matches.length) {
      status.textContent = 'Nothing matches "' + query + '". Try fewer words, or part of a model number.';
      return;
    }
    var shown = Math.min(matches.length, MAX_RESULTS);
    status.textContent = matches.length > shown
      ? 'Showing the closest ' + shown + ' of ' + matches.length + ' matches.'
      : matches.length + (matches.length === 1 ? ' match.' : ' matches.');

    var fragment = document.createDocumentFragment();
    for (var i = 0; i < shown; i++) {
      var doc = matches[i];
      var item = document.createElement('li');
      item.className = 'search-result';

      var link = document.createElement('a');
      link.className = 'search-result-title';
      link.href = urlFor(doc);
      link.textContent = doc[2];

      var meta = document.createElement('p');
      meta.className = 'search-result-meta';
      var label = index.labels[doc[0]];
      meta.textContent = label
        ? index.sections[doc[3]] + ' / ' + label
        : index.sections[doc[3]];

      item.appendChild(link);
      item.appendChild(meta);
      fragment.appendChild(item);
    }
    list.appendChild(fragment);
  }

  function run(raw) {
    var query = normalise(raw);
    if (!query) {
      list.textContent = '';
      status.textContent = 'Type a component, manufacturer, or topic to search ' +
        index.docs.length.toLocaleString() + ' pages.';
      return;
    }
    var tokens = query.split(' ');
    var matches = [];
    for (var i = 0; i < index.docs.length; i++) {
      var doc = index.docs[i];
      if (section !== 'all' && String(doc[3]) !== section) { continue; }
      var points = score(doc, query, tokens);
      if (points > 0) {
        doc.points = points;
        matches.push(doc);
      }
    }
    matches.sort(function (a, b) {
      return b.points - a.points || a[2].localeCompare(b[2]);
    });
    render(matches, raw.trim());
  }

  function load(then) {
    if (index) { then(); return; }
    if (loading) { pending = then; return; }
    loading = true;
    status.textContent = 'Loading the archive index...';

    var request = new XMLHttpRequest();
    request.open('GET', INDEX_URL, true);
    request.onload = function () {
      loading = false;
      if (request.status < 200 || request.status >= 300) { return fail(); }
      try {
        index = prepare(JSON.parse(request.responseText));
      } catch (error) {
        return fail();
      }
      then();
      if (pending) { var next = pending; pending = null; next(); }
    };
    request.onerror = function () { loading = false; fail(); };
    request.send();
  }

  function fail() {
    status.textContent = 'The search index could not be loaded. ' +
      'You can still browse the Hardware Archives and Area 42 directly.';
  }

  var timer = null;
  function schedule() {
    var value = input.value;
    if (timer) { clearTimeout(timer); }
    timer = setTimeout(function () {
      load(function () { run(value); });
    }, 120);
  }

  form.addEventListener('submit', function (event) {
    event.preventDefault();
    if (timer) { clearTimeout(timer); }
    load(function () { run(input.value); });
  });
  input.addEventListener('input', schedule);

  if (filters) {
    filters.addEventListener('click', function (event) {
      var button = event.target.closest('[data-section]');
      if (!button) { return; }
      section = button.getAttribute('data-section');
      var all = filters.querySelectorAll('[data-section]');
      for (var i = 0; i < all.length; i++) {
        all[i].setAttribute('aria-pressed', all[i] === button ? 'true' : 'false');
      }
      load(function () { run(input.value); });
    });
  }

  // Allow /search.html?q=term so results can be linked to directly.
  var match = /[?&]q=([^&]*)/.exec(window.location.search);
  if (match) {
    input.value = decodeURIComponent(match[1].replace(/\+/g, ' '));
  }
  form.hidden = false;
  if (input.value) {
    load(function () { run(input.value); });
  } else {
    status.textContent = 'Type a component, manufacturer, or topic to start searching.';
  }
  input.focus();
})();
